apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-uat
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: notification-uat
  template:
    metadata:
      labels:
        app: notification-uat
    spec:
      containers:
      - image: hour4u/notification-service:uat
        name: notification-uat
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "uat"
        ports:
        - containerPort: 8088
      nodeSelector:
        hour4u-env: uat
      imagePullSecrets:
        - name: regcred-prod