apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  labels:
    app: notification
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8088
    targetPort: 8088
  selector:
    app: notification